/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bugvm.libimobiledevice.binding;

public class InstproxyClientRef {
  private transient long swigCPtr;

  protected InstproxyClientRef(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected InstproxyClientRef() {
    swigCPtr = 0;
  }

  protected static long getCPtr(InstproxyClientRef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

